### ISSUE TITLE
Remover arquivo em branco

### ISSUE THREAD

**Issue by fanny** [OpenDevUFCG/glossario-ufcg#112]
**Descrição da melhoria:**
Não sei se deveria existir uma utilidade pra [esse arquivo](https://github.com/OpenDevUFCG/glossario-ufcg/blob/master/src/styles/material/colors.css), mas atualmente ele é vazio, e é importado apenas no index.

**Comment by thayannevls** [comment]
Realmente não tá sendo usado pra nada, acho que pode remover
