### ISSUE TITLE
Incluir categoria estabelecimento para termos

### ISSUE THREAD

**Issue by thayannevls** [OpenDevUFCG/glossario-ufcg#117]
**Descrição da melhoria:**
Incluir categoria de estabelecimento nos termos, talvez incluindo também o link do Google maps.

**Necessidade da melhoria:**
Estabelecimentos como xerox e restaurantes são úteis para novatos na Universidade que não conhecem.

**Como ela pode ser implementada:**
Adição do termo no json dos dados e adição de campo google maps.

**Comment by fanny** [comment]
vou fechar essa e deixar centralizado na #44
