### ISSUE TITLE
Criaçao de componente para o header

### ISSUE THREAD

**Issue by fanny** [OpenDevUFCG/glossario-ufcg#119]
**Descrição da melhoria:**
Atualmente, nós nao temos um componente para o header, isso é feito via css, dependendo do que a pagina possui.
https://github.com/OpenDevUFCG/glossario-ufcg/blob/3f468202b017983dc5bf593719ef4ca9911cc335/src/components/glossary/GlossaryPage.js#L41
**Necessidade da melhoria:**
Isso dificulta o desenvolvimento de novas paginas que precisem fazer uso do mesmo.

**Como ela pode ser implementada:**
Criar um componente `Header` que só sera exibido, nos componentes em que foi incluido ou a partir de determinada rota.

**Comment by luizcieslak** [comment]
Gostaria de ajudar nessa também, se possível. Minha ideia é separar a div com classe `glossary__search-tools` em um componente, e.g. `<Header />` e criar uma rota para o `/`, o que implica que a homepage também deve ter um componente separado.

**Comment by fanny** [comment]
O caminho é esse mesmo @luizcieslak , não entendi a parte da rota, poderia tentar descrever de outra forma? Vou atribuir ela a você!
