### ISSUE TITLE
Adicionar proptypes nos componentes

### ISSUE THREAD

**Issue by fanny** [OpenDevUFCG/glossario-ufcg#120]
**Descrição da melhoria:**
Seria legal incluir os tipos esperados das propriedades que sao passadas para os componentes

**Comment by luizcieslak** [comment]
Posso ajudar com essa issue!

**Comment by fanny** [comment]
Obrigada @luizcieslak! Vou atribuir ela a você! Se precisar de ajuda é só chamar.
