### ISSUE TITLE
Atualizar componentes de classe para fazerem uso de hooks

### ISSUE THREAD

**Issue by fanny** [OpenDevUFCG/glossario-ufcg#121]
**Descrição da melhoria:**
Seria legal nossos componentes terem um formato mais funcional, tornando-os mais intuitivos e para ajudar com isso, o React provê as [`hooks`](https://pt-br.reactjs.org/docs/hooks-intro.html)

**Comment by JKarlavige** [comment]
I would be happy to help!

**Comment by fanny** [comment]
Hi @JKarlavige! Thanks for the interesting. I will attribute this issue for you! If you need help, you can comment on this thread, and I would be happy to help you
