### ISSUE TITLE
Glossário não está mais responsivo em mobile.

### ISSUE THREAD

**Issue by thayannevls** [OpenDevUFCG/glossario-ufcg#130]
**Descreva o bug**
A interface não está mais se adaptando em telas pequenas, o que é estranho por que antes se adaptava normalmente.

**Reprodução do bug**
Abra glossário no celular ou na parte responsiva do devtools do seu browser.

**Comportamento desejado**
Ser responsivo a tela.

**Capturas de tela**
![Screenshot from 2019-10-09 15-11-41](https://user-images.githubusercontent.com/6867958/66508199-f658db80-eaa6-11e9-9883-ca9872b916d0.png)

**Comment by evelew** [comment]
Oie, eu posso corrigir isso :)

**Comment by thayannevls** [comment]
Opa @evelew muito obrigada! Darei assign em você.

Caso ajude, desconfio que foi nas PRs mais recentes que ficou assim.

**Comment by evelew** [comment]
@thayannevls Oks, vou investigar aqui, obrigada pela dica
