### ISSUE TITLE
Lint falhando e adição de proptypes

### ISSUE THREAD

**Issue by pedroespindula** [OpenDevUFCG/glossario-ufcg#132]
**Descrição da melhoria:**
Extinguir falhas do lint.

**Necessidade da melhoria:**
Deseja-se usar a verificação do lint no travisCI, e, para não quebrar a pipeline, essas falhas devem ser corrigidas.

**Como ela pode ser implementada:**
A maioria dessas falhas está relacionada com a validação de props faltando, com isso, deve-se usar propTypes para validar isto.

**Comment by jonathan-sh** [comment]
@pedroespindula você está implementando? 
Caso não esteja, eu gostaria de resolver essa.

**Comment by pedroespindula** [comment]
Eu tava, mas foi quase nada. Vou me tirar e tu pode fazer.
