### ISSUE TITLE
Suporte a gírias e expressões da universidade

### ISSUE THREAD

**Issue by JoseRenan** [OpenDevUFCG/glossario-ufcg#16]
Atualmente o Glossário está dando suporte aos significados diretos das siglas comumente usadas em ciência da computação na UFCG, porém parte dos termos que os feras não costumam conhecer são gírias e expressões como: bola, leite, tamburete, pijama e etc.

Acredito que não precisaríamos modificar nossa estrutura atual para adicionar isso, porém seria interessante adicionar um atributo que tivesse exemplos de aplicação em frase daquelas expressões para facilitar o entendimento da expressão

**Comment by pedroespindula** [comment]
A inclusão de um campo `atributos adicionais` no objeto resolveria isso. O valor dele seria um array de objetos que conteriam o nome do atributo adicional e o valor daquele atributo. Assim, o próprio card renderizaria todos os atributos adicionais específicos de cada objeto.

**Comment by JoseRenan** [comment]
> A inclusão de um campo `atributos adicionais` no objeto resolveria isso. O valor dele seria um array de objetos que conteriam o nome do atributo adicional e o valor daquele atributo. Assim, o próprio card renderizaria todos os atributos adicionais específicos de cada objeto.

Isso não deixaria confuso caso a gente criasse muitos atributos pra outras coisas extras? tipo links ou slá

**Comment by pedroespindula** [comment]
> > A inclusão de um campo `atributos adicionais` no objeto resolveria isso. O valor dele seria um array de objetos que conteriam o nome do atributo adicional e o valor daquele atributo. Assim, o próprio card renderizaria todos os atributos adicionais específicos de cada objeto.
> 
> Isso não deixaria confuso caso a gente criasse muitos atributos pra outras coisas extras? tipo links ou slá

Acredito que possa ficar um pouco confuso para a manutenção do data.js sim. Outra maneira de resolver isso é adicionando um atributo descrição em si contendo tudo.

**Comment by pedroespindula** [comment]
Para facilitar o entendimento estão aqui exemplos de aplicação da ideia de `atributos extra` e da ideia da `descrição`

- Atributos extra:
```
CC: [{
        acronym: 'CC',
        meaning: 'Ciência da Computação',
        type: 'Curso'
        extra: [
            {
                name: "Link para o site",
                value: "https://wwww.computacao.ufcg.edu.br",
            },
            {
                name: "Data de criação",
                value: "1968",
            },
        ]
    }]
```
- Descrição:
```
CC: [{
        acronym: 'CC',
        meaning: 'Ciência da Computação',
        type: 'Curso'
        description: "Curso criado em 1968. Para mais informações entre no link: https://wwww.computacao.ufcg.edu.br"
    }],
```

**Comment by JoseRenan** [comment]
Nesse caso a gente incluiria as aplicações em frases também na descrição? A propósito, é uma boa discutir também se é útil ter as aplicações em frases nos termos ou se a definição já seria suficiente

**Comment by thayannevls** [comment]
> Nesse caso a gente incluiria as aplicações em frases também na descrição? A propósito, é uma boa discutir também se é útil ter as aplicações em frases nos termos ou se a definição já seria suficiente

Sou a favor de ter aplicações em frases sempre, até porque podemos incluir algumas frases engraçadas e irônicas. Mas mediria os esforços em mexer nesse Json, já que provavelmente depois da SdF iremos implementar um Banco e uma API

**Comment by thayannevls** [comment]
Sou a favor da segunda estrutura mostrada por @pedroespindula , junto com o array de Aplicações de frases.

**Comment by JoseRenan** [comment]
Então fica assim a nova estrutura:
```js
CC: [{
        acronym: 'CC',
        meaning: 'Ciência da Computação',
        type: 'Curso'
        description: "Curso criado em 1968. Para mais informações entre no link: https://wwww.computacao.ufcg.edu.br"
         examples: ["Eu vou fazer CC", "Esse daí é ferinha de CC"]
    }]
```
Todos de acordo?

**Comment by JoseRenan** [comment]
Considerando uma nova estrutura, independente de qual escolhamos, também acho que terríamos de rever o layout por não termos espaço na tela suficiente pra mostrar todas as novas informações e tal... Pensando nisso, fiz uns protótipos de como organizar a informação na tela (sem pensar em cores fontes e etc). Seguem abaixo dois exemplos:

![image](https://user-images.githubusercontent.com/11728746/52894341-96fc3300-3186-11e9-8500-23dc87aec2c2.png)

![image](https://user-images.githubusercontent.com/11728746/52894344-9d8aaa80-3186-11e9-9541-3b496d86a2fc.png)

Se considerarmos exibir os resultados um abaixo do outro não precisaremos pensar em responsividade para exibir os resultados.

Também considero que seja importante com os novos dados termos uma nova rota para mostrar os resultados, ela teria a barra de pesquisa no topo e os resultados embaixo.

O que acham?

**Comment by juliobguedes** [comment]
> Considerando uma nova estrutura, independente de qual escolhamos, também acho que terríamos de rever o layout por não termos espaço na tela suficiente pra mostrar todas as novas informações e tal... Pensando nisso, fiz uns protótipos de como organizar a informação na tela (sem pensar em cores fontes e etc). Seguem abaixo dois exemplos:
> 
> ![image](https://user-images.githubusercontent.com/11728746/52894341-96fc3300-3186-11e9-8500-23dc87aec2c2.png)
> 
> ![image](https://user-images.githubusercontent.com/11728746/52894344-9d8aaa80-3186-11e9-9541-3b496d86a2fc.png)
> 
> Se considerarmos exibir os resultados um abaixo do outro não precisaremos pensar em responsividade para exibir os resultados.
> 
> Também considero que seja importante com os novos dados termos uma nova rota para mostrar os resultados, ela teria a barra de pesquisa no topo e os resultados embaixo.
> 
> O que acham?

Assim ficou bem show
