### ISSUE TITLE
Adicionar links levando a mapas para termos que representam locais

### ISSUE THREAD

**Issue by juliobguedes** [OpenDevUFCG/glossario-ufcg#18]
Foi levantado o tópico sobre ter mais informações, de modo que ao mostrar o que a sigla significa, mostrar também uma breve explicação sobre o que é. Além disso, modificações para incluir hiperlinks levando à mapas, para o exemplo de siglas de blocos (e.g. CAA), devem também ser feitas.

**Comment by thayannevls** [comment]
Parecido com o que foi discutido #16

**Comment by JoseRenan** [comment]
Vou renomear a issue e editar a descrição pra tratar de mapas e localização, já que a parte de descrição já está sendo discutida no #16

**Comment by JoseRenan** [comment]
Update: a ideia é que na versão pós nova ui a gente adicione atributos específicos de cada tipo de termo, e nos locais a gente teria o link no maps, ou coisas do tipo, até pra gente plotar um mapinha se possível. Mas por enquanto, a gente tá tentando descrever o local mais verbalmente mesmo, por exemplo, LCC3 seria o bloco que fica por trás do LSD... etc

**Comment by thayannevls** [comment]
Sugestão: Qualquer termo ter o campo "referencia" ou "verMais", acho que seria melhor.

**Comment by juliobguedes** [comment]
> Update: a ideia é que na versão pós nova ui a gente adicione atributos específicos de cada tipo de termo, e nos locais a gente teria o link no maps, ou coisas do tipo, até pra gente plotar um mapinha se possível. Mas por enquanto, a gente tá tentando descrever o local mais verbalmente mesmo, por exemplo, LCC3 seria o bloco que fica por trás do LSD... etc

A gente vai tipar isso de alguma forma? Flow, TS, ...

**Comment by JoseRenan** [comment]
> A gente vai tipar isso de alguma forma? Flow, TS, ...

Eu tava pensando sobre só definir no contributing msm, até pq os dados tão em .json, só se a gente tipasse só no código (o que é uma boa, se não deixar a contribuição complicada pra React newcomers), essa issue pode se tornar uma discussão sobre isso de adicionar os atributos btw, e quais atributos seriam legais pra adicionar no locais.json

**Comment by pedroespindula** [comment]
Ao adicionar o suporte a MD, foi posssibilitado a colocação de links, com isso pode-se colocar a localização através de um link no maps. No entanto, essa issue ainda é valida para adicionar esses llinks nos locais que estão faltando.

**Comment by juliobguedes** [comment]
Closed by #82.
