### ISSUE TITLE
Ordenar o arquivo com os dados dos termos alfabeticamente

### ISSUE THREAD

**Issue by JuanBarros2** [OpenDevUFCG/glossario-ufcg#19]
Acredito que o nosso arquivo de dados que contém os significados está crescendo bastante e não teremos um bom controle se crescer mais. Gostaria de sugerir a correção do formato para que fosse utilizado uma lista em ordem alfabética para evitar duplicações e retrabalho.

**Comment by JoseRenan** [comment]
Concordo. A forma rápida de fazer isso é rodar um scriptzinho pra ordenar e gerar o novo JSON e mandar PR pro `data.js`, vou marcar como good first issue e renomear a issue

**Comment by juliobguedes** [comment]
Vou fazer esse script aqui, logo mais mando um PR
