### ISSUE TITLE
Erro 404 ao acessar a página "Quem somos?"

### ISSUE THREAD

**Issue by felipegangorra** [OpenDevUFCG/glossario-ufcg#206]
Not Found ao tentar acessar a página referente a "Quem somos?", presente na página inicial do glossário.

<br>

![not-found-glossario](https://github.com/OpenDevUFCG/glossario-ufcg/assets/87813261/f63ba3df-faf9-414b-aec2-e912deb57acb)

**Comment by LeandraOS** [comment]
Muito obrigada @gangorra por reportar essa issue, iremos divulgar ela para a comunidade conseguir contribuir :rocket:
