### ISSUE TITLE
Adicionando giria "Fumo"

### ISSUE THREAD

**Issue by felipegangorra** [OpenDevUFCG/glossario-ufcg#207]
#### Nome do termo:

 Fumo
#### Significado do termo:

Que algo foi/é difícil e se deu mal.

#### Descrição:

O termo é usado pelos alunos para descrever uma experiência difícil em que se deu mal ou vai se dar mal.
Muito aplicado para definir disciplinas e/ou avaliações ruins. 
#### Tipo:

- [ ] Curso
- [ ] Disciplina
- [X] Giria
- [ ] Local
- [ ] Outro

#### Exemplo de aplicação em frase:

Cálculo é fumo.
Levei fumo na prova de Direito.

**Comment by LeandraOS** [comment]
Muito obrigada @gangorra por reportar essa issue :rocket: esperamos contar com suas contribuições!
