### ISSUE TITLE
Separar os dados dos termos em várias coleções

### ISSUE THREAD

**Issue by alvesmatheus** [OpenDevUFCG/glossario-ufcg#21]
Atualmente os dados do data.js estão acumulando siglas, blocos, gírias, disciplinas, etc numa só coleção. Porém, cada tipo de termo requer uma estrutura específica e essa abordagem também dificulta a contribuição... Por isso, qual seria a melhor forma de reestruturar esses dados?

**Comment by thayannevls** [comment]
Gostei muito da ideia, acho que iria facilitar muito o entendimento, fico na dúvida se seria bom separar entre siglas e gírias, já que sigla e gíria podem ser disciplinas, locais e etc.

**Comment by juliobguedes** [comment]
Acho que vale a pena separar, ainda no `data.js`, entre alguns arrays específicos e exportar os específicos também, e não só o default de acronimos, como é atualmente. Mas, como @thayannevls disse, creio que facilite separar, mas discordo separar apenas entre sigla (que inclui locais, disciplinas e outras coisas) e gírias, que são apenas nossas expressões... Acho que fica melhor separar: locais, gírias e expressões comuns, disciplinas obrigatórias, disciplinas optativas e `legacy`, que seriam coisas do PPC antigo: AD1, por exemplo, atualmente se refere à CDD.

**Comment by JoseRenan** [comment]
Outra sugestão que foi feita foi separar por type, considerando definir types fixos que nuca mudaremos como disciplina, local, gíria, curso e outros (que seria uma categoria pros que não se encaixam em nenhum)

**Comment by juliobguedes** [comment]
Gente, eu sugiro/proponho que, junto a essa issue, os dados da gente sejam mantidos em arquivos `.json`... Isso ajudaria a refatorar o script que eu fiz de ordenar as chaves do arquivo pra rodar automaticamente por nn precisar do package que eu usei, e ainda assim eles podem ser importados pelos arquivos js sem causar problemas... posso pegar essa issue quando for decidido as categorias que separaremos os dados

**Comment by JoseRenan** [comment]
@juliobguedes por mim tá top... dividiríamos os dados em 5 arquivos json: 

- Disciplinas (Para siglas e nomes de disciplinas)
- Locais (Para siglas e nomes de locais da UFCG)
- Gírias (Para gírias que usamos no dia a dia da universidade)
- Cursos (Para siglas e nomes de cursos)
- Outros (Para os que não se encaixarem em nenhuma outra categoria KKKKK)

É bom levar em consideração que talvez possa haver o caso de existir uma disciplina que tenha a mesma sigla de um lugar por exemplo.

**Comment by JoseRenan** [comment]
> É bom levar em consideração que talvez possa haver o caso de existir uma disciplina que tenha a mesma sigla de um lugar por exemplo.

Ou seja, ter um cuidado extra na hora de juntar os arrays e estar preparado para esse caso

**Comment by JoseRenan** [comment]
Resolvido no #35
