### ISSUE TITLE
Roteamento de termos não está funcionando corretamente

### ISSUE THREAD

**Issue by thayannevls** [OpenDevUFCG/glossario-ufcg#25]
Ao pesquisar um termo, ele deveria colocar em `https://opendevufcg.github.io/glossario-ufcg/<termo>`, mas ao invés disso ele faz `https://opendevufcg.github.io/<termo>` e retorna erro 404.

**Comment by JoseRenan** [comment]
Right, esse problema não acontece em ambiente de desenvolvimento, só em produção.
[Isso](https://medium.com/@Dragonza/react-router-problem-with-gh-pages-c93a5e243819) deve resolver

**Comment by JoseRenan** [comment]
Dando reopen pq deu negado o #26 kkkkkkkkkkkkkkkkkk

**Comment by thayannevls** [comment]
KKKKKKKKKKKKKKKKKKK

**Comment by pedroespindula** [comment]
#### Causa do problema:

O github pages não suporta o roteamento do jeito que está sendo feito agora. [Link para mais informações](https://itnext.io/so-you-want-to-host-your-single-age-react-app-on-github-pages-a826ab01e48).

#### Possiveis soluções:

Soluções propostas pela propria documentação do React.

- Substituir o BrowserRouter pelo HashRouter. No entanto, a rota iria ficar `/#/<termo` ao inves de `/<termo>`.
- Adicionar um 404.html que redirecionaria para o index.html com o termo passado. Poderia gerar bugs e ficaria complexo.

Outra solução possivel:
- Usar um servidor para servir a pagina ao invés do github page. Isso iria gerar um trabalho extra com o Travis para deploy mas daria mais controle quanto a aplicação.

**Comment by JoseRenan** [comment]
Ping @paulojbleitao

**Comment by JoseRenan** [comment]
Eu acho que não seria uma boa ideia tirar do gh-pages agora, e aho que o 404.html é uma gambiarra triste KKKKKKK Acho que nn é um problema passar pra hashrouter
