### ISSUE TITLE
Outros types para o data.js

### ISSUE THREAD

**Issue by alvesmatheus** [OpenDevUFCG/glossario-ufcg#3]
Seria legal criar uma listinha dos types existentes (com a definição do que ele contém) e como definir novos types... Por exemplo, pra colocar PRE no data.js, qual seria o type adequado?

**Comment by thayannevls** [comment]
Verdade, vou criar um documento com os que já foram colocados e como sugerir novos. Confesso que ainda não sei bem que types abordar kkk.

Até agore pensei em:

- Local (Que poderia envolver Salas, blocos e etc)
- Disciplina
- ? Período ? (p1, p2..)
- Curso
- ...

**Comment by JoseRenan** [comment]
Vou fechar a issue discutirmos melhor na #21
