### ISSUE TITLE
Criar um issue template especial para adição de termo

### ISSUE THREAD

**Issue by thayannevls** [OpenDevUFCG/glossario-ufcg#41]
**Descrição da melhoria:**
Algumas pessoas apenas querem sugerir a adição de um termo para que outra pessoa adicione nossos dados. Seria interessante criar um **issue template** especial para esse tipo de request, que a pessoa preencha direitinho esses campos:

- Nome do termo
- Significado
- Descrição
- Tipo (Mostrar os tipos que tem pra ele escolher, pode ser um checkbox que ele marca o que ele quer)
- Exemplos com as aplicações de frase

**Comment by pedroespindula** [comment]
Isso tem relação com a #32. (Comentário feito apenas para referenciamento da Issue)
