### ISSUE TITLE
Preencher e melhorar os dados de termos que possuimos

### ISSUE THREAD

**Issue by JoseRenan** [OpenDevUFCG/glossario-ufcg#44]
Bem, vamos começar com uma historinha... Inicialmente a gente pensava no glossário apenas como um site pra gente descobrir o que significa algumas siglas do curso de computação... porém com o tempo a gente viu que tem muitos outros termos que poderíamos adicionar como gírias da universidade e etc. Por causa disso, maioria dos nossos dados continham apenas a sigla e o que ela significa "por extenso" por exemplo: P1 -> Programação 1 e etc...

Percebemos depois que algumas siglas não fazem tanto sentido se apenas dissermos o que ela significa por extenso, precisamos dar uma descrição mais detalhada... por exemplo:
P1 -> Programação 1 -> Disciplina do 1º período de ciencia da computação que [...]
Um texto curtinho apenas para ficar claro para o leitor do que se trata o termo.

Também precisamos adicionar aplicações em frases para todos os termos que já temos, conforme o padrão [na nossa documentação dos dados](https://github.com/OpenDevUFCG/glossario-ufcg/blob/master/docs/TERMO.md) (nessa parte pode esquecer a seriedade e tentar ser engraçadinho, mas sem desrespeitar ninguém taokei?).

**[EDIT]** Se você caiu nessa issue antes de ver nosso README, seria uma boa dar uma olhada no nosso [CONTRIBUTING.md](https://github.com/OpenDevUFCG/glossario-ufcg/blob/master/CONTRIBUTING.md) pra ver como a gente organiza os dados e etc... Se tiver problemas com git ou com qualquer outra coisa sobre como ajudar nessa task, pode falar com a gente no [gitter](https://gitter.im/OpenDevUFCG/glossario-ufcg) que a gente te ajuda!!!

**[EDIT2]** Podem seguir o padrão do PR #47 

Segue abaixo a lista de termos que ainda estão faltando esses dados:

### Cursos:

- [x] CC Ciência da Computação

### Disciplinas:

Para a descrição das disciplinas não precisa de muita informação, basta informar qual período ela é ofertada, se é obrigatória ou optativa, se existe com outro nome na nova grade ou na grade antiga... essas curiosidades pequenas só pra contextualizar.

- [x] AA Algoritmos Avançados
- [ ] ADSD Avaliação de Desempenho de Sistemas Discretos
- [x] AS Análise de Sistemas
- [x] ATAL Análise e Técnicas de Algoritmos
- [x] BD Banco de Dados I
- [ ] BD2 Banco de Dados II
- [x] CDD Ciência de Dados Descritiva
- [x] CDP Ciência de Dados Preditiva
- [ ] CG Computação Gráfica
- [x] DACA Desenvolvimento de Aplicações Corporativas Avançadas
- [x] EDA Estrutura de Dados e Algoritmos
- [x] ES Engenharia de Software
- [ ] ETI Economia de Tecnologia da Informação
- [x] FMCC1 Fundamentos de Matemática para Ciência da Computação I
- [x] FMCC2 Fundamentos de Matemática para Ciência da Computação II
- [ ] GR Gerência de Redes
- [x] IA Inteligência Artificial
- [x] IC Introdução à Computação
- [ ] IRC Interconexão e Redes de Computadores
- [ ] JoDi Jogos Digitais
- [x] LEDA Laboratório de Estrutura de Dados e Algoritmos
- [x] LOAC Laboratório de Organização e Arquitetura de Computadores
- [x] LP1 Laboratório de Programação 1
- [x] LP2 Laboratório de Programação 2
- [x] MSN Métodos e Softwares Numéricos
- [x] OAC Organização e Arquitetura de Computadores
- [x] P1 Programação 1
- [ ] P1 Projeto 1
- [x] P2 Programação 2
- [ ] P2 Projeto 2
- [ ] PC Programação Concorrente
- [x] PLP Paradigmas de Linguagem de Programação
- [x] SAD Sistemas de Apoio à Decisão
- [ ] SO Sistemas Operacionais
- [x] TC Teoria da Computação
- [x] TCC Trabalho de Conclusão de Curso
- [x] TG Teoria dos Grafos
- [ ] VC Visão Computaciona
- [x] VVS Verificação e Validação de Software
+ (#70) 
### Gírias:

Nas gírias, elas só precisam basicamente de mais aplicações em frases, mas se quiserem adicionar mais informações sobre o porquê de usar essa gíria, ou de onde ela surgiu... é muito bem vindo!!!

- [x] BOLA
- [x] LEITE
- [x] PIJAMA

### Locais:

Nas descrições dos locais seria bom ter informações de o que é o local, em que bloco fica por exemplo, ou coisas do tipo "na frente da biblioteca"... e etc, futuramente pensamos em adicionar coordenadas e mostrar um mapa como foi dito na issue #18 mas são cenas dos próximos capítulos....

- [x] LCC1 Laboratório de Ciência da Computação 1
- [x] LCC2 Laboratório de Ciência da Computação 2
- [x] LCC3 Laboratório de Ciência da Computação 3
- [ ] LSD Laboratorio de Sistemas Distribuidos
- [ ] SPLab Software Practices Laboratory
+ (#95)
### Outros:

Nesses eu peço pra tentarem ser o mais descritíveis o possível, pois não temos uma categorização por tipo bem definida, o que complica um pouco mais o entendimento sobre que se trata o termo

- [x] RDM Relação de disciplinas matriculadas
- [x] TECC Tópicos Especiais em Ciência da Computação 
- [ ] SDF Semana do Fera
- [ ] CF CodeForces
- [ ] Contest Contest

VALENDO!!!!!!!!

**Comment by pedroespindula** [comment]
CC - Ciência da Computação - O melhor curso da UFCG

**Comment by JoseRenan** [comment]
Pra galera do @OpenDevUFCG/glossario-ufcg que tiver revisando os PRs, lembrem de marcar os que estão merjando aqui!!

**Comment by thayannevls** [comment]
Vou fazer esses:
- FMCC1
- IC
- FMCC2
- P2
- PLP
- TG

**Comment by lucasmedeiros** [comment]
Vou fazer esses:

- LCC1
- LCC2
- LCC3

**Comment by juliobguedes** [comment]
Update adicionando Semana do Fera

**Comment by fanny** [comment]
Reabrindo! Vamos ajudar, pessoal!

**Comment by fanny** [comment]
Tava pensando se fazia sentido, incluir alguns siglas que a gnt vế aqui no github. Tipo `LGTM` ou `TLDR;` o que acham?
