### ISSUE TITLE
Pode adicionar link pro maps nos significados?

### ISSUE THREAD

**Issue by thayannevls** [OpenDevUFCG/glossario-ufcg#59]
Em termos que são locais, posso adicionar sua localização no google maps através de um link?

Exemplo: LCC3 -> https://goo.gl/maps/AvG7MYGsqZ92

**Comment by JoseRenan** [comment]
Tem uma issue que discute isso #18, o negócio ainda não dá suporte a links, a ideia é que na versão pós nova ui a gente adicione atributos específicos de cada tipo de termo, e nos locais a gente teria o link no maps, ou coisas do tipo, até pra gente plotar um mapinha se possível. Mas por enquanto, a gente tá tentando descrever o local mais verbalmente mesmo, por exemplo, LCC3 seria o bloco que fica por trás do LSD... etc

**Comment by JoseRenan** [comment]
Vou marcar como duplicate do #18 e fechar, blz?
