### ISSUE TITLE
Adicionar Favicon

### ISSUE THREAD

**Issue by pedroespindula** [OpenDevUFCG/glossario-ufcg#6]
Apesar de possuir o arquivo de Favicon no caminho `assets/images/favicon.ico`, o favicon não é mostrado.

**Comment by JoseRenan** [comment]
Oi, @pedroespindula, estamos aguardando @hericlesme finalizar o ícone do glossário, mas no meio tempo podemos adicionar o favicon da organização mesmo, adicionei a label de good first issue

**Comment by thayannevls** [comment]
@JoseRenan @pedroespindula Agora temos um ícone :D

**Comment by JoseRenan** [comment]
Vou reabrir pois na nova UI ainda não está com o favicon

**Comment by pedroespindula** [comment]
O favicon deve ser adicionado ao webpack para funcionar do jeito que deveria.
