### ISSUE TITLE
Adicionar suporte à markdown/html

### ISSUE THREAD

**Issue by juliobguedes** [OpenDevUFCG/glossario-ufcg#60]
**Descrição da melhoria:**
Muitas das coisas que fazemos podem ser auxiliadas com **links**. Tendo isso em vista, é interessante adicionar um suporte à Markdown ou HTML nas descrições.

**Necessidade da melhoria:**
A melhoria é necessária pois, por exemplo, ao adicionarmos lugares (blocos, por exemplo), é interessante adicionarmos links para o google maps indicando a localização. Essa é apenas uma necessidade inicial, e por ajudar bastante os feras, tem grande importância.

**Como ela pode ser implementada:**
É possível implementar facilmente através do uso do [React Markdown](https://github.com/rexxars/react-markdown) ou similares

**Comment by JoseRenan** [comment]
Seria uma boa a gente dar uma olhada se tem como limitar as features do markdown, tipo, evitar headings, só as de formatação de paragrafo mesmo tipo hyperlink, negrito, itálico

**Comment by JoseRenan** [comment]
> Seria uma boa a gente dar uma olhada se tem como limitar as features do markdown, tipo, evitar headings, só as de formatação de paragrafo mesmo tipo hyperlink, negrito, itálico

Isso de desabilitar headings seria mais por questão de não atrapalhar o layout do glossário, vi que tem como desabilitar alguns nodes no react-markdown https://github.com/rexxars/react-markdown#node-types

**Comment by JoseRenan** [comment]
Ping @pedroespindula @paulojbleitao

**Comment by thayannevls** [comment]
> > Seria uma boa a gente dar uma olhada se tem como limitar as features do markdown, tipo, evitar headings, só as de formatação de paragrafo mesmo tipo hyperlink, negrito, itálico
> 
> Isso de desabilitar headings seria mais por questão de não atrapalhar o layout do glossário, vi que tem como desabilitar alguns nodes no react-markdown https://github.com/rexxars/react-markdown#node-types

Mas ai seria trabalho da revisão, não?

**Comment by JoseRenan** [comment]
> Mas ai seria trabalho da revisão, não?

Sim sim, mas se der pra limitar e a revisão nn precisar se preocupar com isso é melhor nn?
