### ISSUE TITLE
Siglas com multiplos sentidos

### ISSUE THREAD

**Issue by pedroespindula** [OpenDevUFCG/glossario-ufcg#7]
Algumas siglas usadas na UFCG tem mais de um sentido. P1, por exemplo, pode ser usada tanto para se referir a cadeira de programação 1, como também sobre a cadeira de Projeto 1, assim como o primeiro periodo do curso.

**Comment by pedroespindula** [comment]
Sugestão: Reestruturar o data.js de forma que o acronym seja um objeto onde a chave seria o "acronym" e o valor seria uma lista de objetos que expressariam o que aquela sigla representaria.
- Exemplo:
```
const exampleData = {
    "P1": [
        {
            acronym: "P1",
            meaning: "Programação 1",
            type: "Disciplina",
        },
        {
            acronym: "P1",
            meaning: "Projeto 1",
            type: "Disciplina",
        },
        {
            acronym: "P1",
            meaning: "1° Periodo do curso",
            type: "Giria",
        },
    ]
};
```

**Comment by pedroespindula** [comment]
Além disso, a reestruturação do data.js desse modo, facilitaria a ordenação das chaves para a sua exibição na caixa de pesquisa.

**Comment by JoseRenan** [comment]
Ótima sugestão, acredito que ao reestruturar pra aceitar múltiplos significados, poderíamos adicionar um atributo com aplicação em frases também, pra expressões como "rasgar", "rasguei a prova de estatística", o que acham?

**Comment by JoseRenan** [comment]
Ping @paulojbleitao @thayannevls

**Comment by thayannevls** [comment]
Acho ótimo @JoseRenan . Haveria objetos diferentes pra sigla e gírias? Ou bota tudo num só?

**Comment by pedroespindula** [comment]
> Acho ótimo @JoseRenan . Haveria objetos diferentes pra sigla e gírias? Ou bota tudo num só?

Eu acho que colocaria-se tudo num objeto do mesmo "tipo" digamos assim. Iriam só ter alguns campos diferentes mas seriam passados pra o componente Description do mesmo jeito e ele quem se encarregaria de mostrar os dados referentes aquele objeto.

**Comment by thayannevls** [comment]
Bem, então acho que só renomear o objeto de `acronyms` pra `terms`.

Essa issue foi resolvida em #10 né? Então acho que pode fechar

**Comment by pedroespindula** [comment]
> Bem, então acho que só renomear o objeto de `acronyms` pra `terms`.
> 
> Essa issue foi resolvida em #10 né? Então acho que pode fechar

Não completamente, a reestruturação no data.js foi feita, mas está faltando integrar o front com a alteração adicionando a navigation bar e as setas pra trocar os sentidos.
