### ISSUE TITLE
Adicionar optativas Gerais

### ISSUE THREAD

**Issue by jonathantvrs** [OpenDevUFCG/glossario-ufcg#70]
Pessoal, as optativas gerais não vão ser adicionadas?

[EDIT]

A seguinte lista de optativas gerais não está ainda no glossário:

(Se alguma das disciplinas listadas não for uma optativa geral, ou não fizer sentido estar aqui, comente abaixo)

- [ ] Língua Portuguesa (antes Leitura e Produção de Textos)
- [ ] Informática e Sociedade
- [ ] Economia
- [ ] Direito e Cidadania
- [ ] Inglês
- [ ] Administração e Empreendedorismo
- [ ] Administração

**Comment by JoseRenan** [comment]
Serão adicionadas sim, a gente adicionou todas que encontramos num documento das disciplinas ofertadas, e algumas da antiga grade, mas não achamos o documento com as Gerais, inclusive se tiver algumas pra listar, pode dizer aqui que alguém adiciona!!!

**Comment by JoseRenan** [comment]
Algumas que eu conheço são:

- Lingua Portuguêsa (antes Leitura e Produção de Textos)
- Informática e Sociedade

Algumas que eu não sei se são gerais:

- Economia

**Comment by jonathantvrs** [comment]
- Economia
- Direito e Cidadania
- Inglês

**Comment by jonathantvrs** [comment]
- Administração e Empreendedorismo
- Administração

E sim, parece que tem as duas e são diferentes

**Comment by JoseRenan** [comment]
Vou editar a descrição pra colocar um checklist das optativas a serem adicionadas, assim como tá na #44
