### ISSUE TITLE
Adicionar termos relacionados ao github e contribuições

### ISSUE THREAD

**Issue by JoseRenan** [OpenDevUFCG/glossario-ufcg#77]
#### Nome dos termos:
Fork, PR, Issue, Commit (e outros que acharem interessantes)

#### Contexto adicional:
Esses termos foram solicitados por feras que procuraram no glossário alguns termos que acharam nos nossos readmes e não encontraram... Seria mto bom ter eles aqui

**Comment by pedroespindula** [comment]
- Mais termos para serem adicionados.
1. SEI: Sistema Eletronico de Informações 
1. PRE: Pro Reitoria de Ensino
1. CEEI: Coordenação de Engenharia Eletrica e Informatica
1. AMARELINHA: Xerox Amarelinha
1. Laguinho

**Comment by JoseRenan** [comment]
> CEEI: Coordenação de Engenharia Eletrica e Informatica

Esse já tem :thinking:
