### ISSUE TITLE
Adicionar novos termos

### ISSUE THREAD

**Issue by juliobguedes** [OpenDevUFCG/glossario-ufcg#83]
Adicionar termos pedidos por @pedroespindula na #77 

#### Nome do termo:

* SEI: Sistema Eletronico de Informações
* PRE: Pro Reitoria de Ensino
* CEEI: Coordenação de Engenharia Eletrica e Informatica
* AMARELINHA: Xerox Amarelinha
* Laguinho

**Comment by pedroespindula** [comment]
ATG: Aplicação de Teoria dos Grafos

**Comment by juliobguedes** [comment]
APLP: Aplicação de Paradigmas de Linguagem de Programação

**Comment by pedroespindula** [comment]
RI: Recuperação da Informação
