### ISSUE TITLE
Adicionar efeito de hover nos botões

### ISSUE THREAD

**Issue by thayannevls** [OpenDevUFCG/glossario-ufcg#88]
**Descrição da melhoria:**
Os Links "Como Contribuir" e "Quem Somos" podem ter um efeito de hover simples e minimalista.

**Necessidade da melhoria:** Melhorar o design da página e passar melhor a impressão que é "clicavel"
**Como ela pode ser implementada:** Talvez um efeito que mude um pouco a cor para mais clara ou escura

**Comment by pedroespindula** [comment]
#92 Fixes
