### ISSUE TITLE
Adicionar efeito ao passar o mouse no termo em "Você sabe..." 

### ISSUE THREAD

**Issue by thayannevls** [OpenDevUFCG/glossario-ufcg#89]
**Descrição da melhoria:**
Quando passar o mouse no termo que aparece em "Você sabe o que é ..." era bom adicionar algum efeito ao passar o mouse por cima (hover)

**Necessidade da melhoria:** para passar melhor a impressão de clicável

**Como ela pode ser implementada:**
Talvez sublinhá-lo ao passar o mouse

**Comment by JoseRenan** [comment]
Deixar ele levemente mais claro seria toptop
