### ISSUE TITLE
Adicionar localizações de termos do tipo "local"

### ISSUE THREAD

**Issue by pedroespindula** [OpenDevUFCG/glossario-ufcg#93]
**Descrição da melhoria:**
A maioria dos termos do tipo `local` não possui uma localização. A melhoria é adicionar a esses termos essa localização.

**Necessidade da melhoria:**
Facilitar a identificação e acesso do local pelos estudantes.

**Como ela pode ser implementada:**
Seguir o modelo implementado no termo `LCC1`, que usa de um link no maps para mostrar a localização. Esse link é usado como um link comum em MarkDown, ou seja: 
`[nome do link](https://link.com)`
Para descobrir o link da localização, vá no google maps e procure pela UFCG. Ao encontra-la procure pelo local a qual você quer conseguir a localização e ao encontra-lo clique nele. Esse será o link da localização.

**Imagens:**
- Termo com localização já implementada:
![Screenshot from 2019-03-29 21-56-04](https://user-images.githubusercontent.com/38431219/55268960-7b984380-526d-11e9-9d54-cc6dcdf6363f.png)

- Localização quando acessada:
![Screenshot from 2019-03-29 21-54-48](https://user-images.githubusercontent.com/38431219/55268948-658a8300-526d-11e9-92e8-401c7fc673a9.png)

**Comment by RaylaMedeiros** [comment]
Não seria mais simples se houvesse um atributo no json pra o link da localização?

**Comment by thayannevls** [comment]
Também acho @RaylaMedeiros , também facilitaria pra no futuro mostrar a miniatura do google maps no site

**Comment by pedroespindula** [comment]
Foi adotado um modelo padrão para todas os termos e por isso não existe hoje esse atributo, mas é realmente uma boa ideia. Uma ideia dada por @ivynasantino foi que fosse criado um campo para atributos auxiliares como a `localização`, que seria um objeto onde a chave seria o nome do atributo e o valor, o valor do atributo.

**Comment by JoseRenan** [comment]
A ideia inicial quando dividimos em vários JSON foi que tivesse uma estrutura padrão que todos os JSON teria e cada um teria os atributos específicos, tipo, o de disciplinas poderia ter link pro tamburetei por exemplo, o de locais poderia ter a geolocalização e etc, isso foi discutido em alguma issue, porem nunca implementado
